name: Build and push to ECR
description: Build and push to ECR

inputs:
  ecr_repo:
    required: true
    type: string
    default: 963800667800.dkr.ecr.us-east-2.amazonaws.com
  image_tag:
    required: true
    type: string
  dockerfile:
    required: true
    type: string
  server_name:
    required: true
    type: string

runs:
    using: composite
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials from dev account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::708050157146:role/github_eb_ci_cd
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: ECR Login
        shell: bash
        run: | 
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ inputs.ecr_repo }}        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.ecr_repo }}/${{ inputs.server_name }}:${{ inputs.image_tag }},${{ inputs.ecr_repo }}/${{ inputs.server_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
