version: '3.8'

services:
  app:
    image: node:20-alpine
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/sh -c "npm install && npm run start:dev"

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    command:
      - "http"
      - "app:3000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    depends_on:
      - app
