version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION:-18}
        PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    command:
      - "http"
      - "app:${PORT:-3000}"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    depends_on:
      - app
