name: Deploy task definition
description: Build task definition

inputs:
  task_definition_version:
    required: true
    type: string
  region:
    required: true
    type: string
  environment:
    required: true
    type: string
  service_name:
    required: true
    type: string


runs:
    using: composite
    steps:
    - name: Deploy detached
      shell: bash
      run: |
        ./deploy_detached.sh ${{ inputs.region }} fpjs-${{ inputs.environment }}-${{ inputs.service_name }} 0 ${{ inputs.task_definition_version }}